[tool.isort]
line_length = 120
multi_line_output = 3
lines_after_imports = 2
combine_star = true
include_trailing_comma = true
star_first = true
import_heading_future = "Future"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Packages"
import_heading_firstparty="My stuff"
import_heading_localfolder="My stuff"
