name: Verify Types

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:

  job:
    name: "Verify Types @ Python v${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:

      # git

      - name: "Initialise Environment"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # node

      - name: "Setup Node v18"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install Pyright"
        run: |
          npm install -g pyright@latest

      # python

      - name: "Setup Python v${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Poetry"
        run: |
          pipx install poetry==1.2.0b3

      - name: "Install Dependencies"
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install

      - name: "Verify types"
        run: |
          poetry run pyright
          poetry run pyright --ignoreexternal --lib --verifytypes slate
